language: java
install: true

os: linux
dist: bionic
jdk: openjdk11

script:
  - export JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
  - ./gradlew --no-daemon build check --stacktrace
  
after_success:
  - bash <(curl -s https://codecov.io/bash)